apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-volume-claim
  labels:
    name: my-grafana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi